# Generated by Django 4.2.4 on 2023-08-31 18:34

from django.db import migrations, models
import django.db.models.deletion
import restaurants.file_path


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DishModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="DishReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.SmallIntegerField(default=1)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.dishmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrinterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "serial_num",
                    models.CharField(max_length=64, verbose_name="Serial Number"),
                ),
                ("brand", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=256)),
                ("dishes", models.ManyToManyField(to="restaurants.dishmodel")),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.SmallIntegerField(choices=[(0, "client"), (1, "kitchen")]),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Not Generated"), (1, "Generated")]
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to=restaurants.file_path.get_pdf_file_path),
                ),
                (
                    "dishes",
                    models.ManyToManyField(
                        through="restaurants.DishReceipt", to="restaurants.dishmodel"
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="restaurants.printermodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="printermodel",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printers",
                to="restaurants.restaurantmodel",
            ),
        ),
        migrations.AddField(
            model_name="dishreceipt",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.receiptmodel",
            ),
        ),
    ]
