# Generated by Django 4.2.4 on 2023-08-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DishReceipt",
            new_name="DishReceiptModel",
        ),
        migrations.RemoveField(
            model_name="receiptmodel",
            name="printer",
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="restaurants.restaurantmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receiptmodel",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Not Generated"), (1, "Generated")], default=0
            ),
        ),
    ]
