# Generated by Django 4.2.4 on 2023-09-01 08:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_rename_dishreceipt_dishreceiptmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishOrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="printers",
            field=models.ManyToManyField(to="restaurants.printermodel"),
        ),
        migrations.AlterField(
            model_name="dishmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dishes",
                    models.ManyToManyField(
                        through="restaurants.DishOrderModel", to="restaurants.dishmodel"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="restaurants.restaurantmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dishordermodel",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_orders",
                to="restaurants.dishmodel",
            ),
        ),
        migrations.AddField(
            model_name="dishordermodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_dishes",
                to="restaurants.ordermodel",
            ),
        ),
        migrations.AddField(
            model_name="receiptmodel",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="restaurants.ordermodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="receiptmodel",
            unique_together={("order", "type")},
        ),
        migrations.RemoveField(
            model_name="receiptmodel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="receiptmodel",
            name="dishes",
        ),
        migrations.RemoveField(
            model_name="receiptmodel",
            name="restaurant",
        ),
        migrations.DeleteModel(
            name="DishReceiptModel",
        ),
    ]
