# Generated by Django 4.2.4 on 2023-09-01 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_dishordermodel_receiptmodel_printers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dishordermodel",
            old_name="amount",
            new_name="quantity",
        ),
    ]
